api_platform:
    title: 'Symfony REST API'
    description: 'Test API Symfony par Allin'
    version: '1.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
